# Generated by Django 4.2.6 on 2023-10-30 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
    ]
